### ISSUE TITLE
Row selection by Check box - Select all

### ISSUE THREAD

**Issue by Varada-Echidna** [Swimlane/angular-data-table#213]
Row selection by Check box (header checkbox)  Select all checkbox will allow us to select all the rows in table, But if we uncheck even one from the rows,  Header checkbox should be unchecked which is not happening. Please can you help.

Thanks and regards,
Varada

**Comment by guo-guo** [comment]
Problem has been solved?

**Comment by guo-guo** [comment]
Problem has been solved?   I have the same problem with you

**Comment by Varada-Echidna** [comment]
Problem is not Solved. Requesting @amcdnl , @marjan-georgiev , @Thrilleratplay, @brianfeister Please help on this. 

Thanks and Regards,
Varada

**Comment by amcdnl** [comment]
@Varada-Echidna PR welcome, I don't have time to fix this at the moment

**Comment by Varada-Echidna** [comment]
How to start editing the code - Please help me start. i will have the code written and will pull. @amcdnl

**Comment by jonshaffer** [comment]
Just FYI - I have requirements for an indeterminate and can have a PR for this today (but not with the material style update)

**Comment by Varada-Echidna** [comment]
@properjon - Hey did you push your code !? solving this bug !?

Thanks and Regards,
Varada

**Comment by jonshaffer** [comment]
@Varada-Echidna thanks for the ping, I've been under a few distractions unfortunately.

You can check out the differences in my fork if you want a starting point for a potential solution to tackle yourself - I've found this to be not entirely trivial.

Cheers

**Comment by jonshaffer** [comment]
@Varada-Echidna There is a working fix in a PR - #240

**Comment by svassr** [comment]
I'd like to see that merged.
