### ISSUE TITLE
font-weight on First row looks different

### ISSUE THREAD

**Issue by msuntharesan** [Swimlane/angular-data-table#22]
![angular data table](https://cloud.githubusercontent.com/assets/1296183/8600817/0918edee-2636-11e5-96d4-43616edfe3ef.png)

**Comment by amcdnl** [comment]
Minor CSS deal in material proj.

**Comment by GuiHash** [comment]
I have the same issue but i don't think it's due to CSS.
The first row is repeating twice (see capture : 2 rows and 3 elements).
![bug-data-table](https://cloud.githubusercontent.com/assets/4471444/9316771/0a515a9e-452f-11e5-87ae-b0805bd9212d.png).

**Comment by amcdnl** [comment]
Oh wow, I saw this when prototyping some perf improvements but thought it was just something I did!

**Comment by msuntharesan** [comment]
Actually this is not just the first row.

When scrolling is involved, this happens to items beyond the initial view. This became more clear when I changed the css for cell-content

![data-table doubling 1](https://cloud.githubusercontent.com/assets/1296183/9361277/a6d07d52-4668-11e5-8ddf-6b6eee32ffee.jpg)

![data-table doubling 2](https://cloud.githubusercontent.com/assets/1296183/9360937/21af06e4-4667-11e5-8857-f919e171249a.jpg)

**Comment by msuntharesan** [comment]
Also it seems that the rows are getting re-rended again and again on every scroll

**Comment by amcdnl** [comment]
Test latest, this is fixed

**Comment by msuntharesan** [comment]
Thanks. That did fix the first row. But this is still happening to rows that are beyond initial visible scroll area. 

![data-table doubles](https://cloud.githubusercontent.com/assets/1296183/9362033/53da1da2-466c-11e5-92eb-29feef4f5b91.gif)

**Comment by amcdnl** [comment]
@vanthiyathevan  Can you create a demo that shows that plz?

**Comment by msuntharesan** [comment]
Will do

**Comment by msuntharesan** [comment]
[Code Demo](http://codepen.io/vanthiyathevan/pen/yNdNEw) for this bug. Scroll all the way to the bottom to see the issue.

**Comment by amcdnl** [comment]
Fixed in 0.3.9

**Comment by msuntharesan** [comment]
Thank you. Although this is fixed only when `scrollbarV` is `true`. When it is false [This](https://cloud.githubusercontent.com/assets/1296183/9361277/a6d07d52-4668-11e5-8ddf-6b6eee32ffee.jpg) is hapening.

![data-table doubling 1](https://cloud.githubusercontent.com/assets/1296183/9361277/a6d07d52-4668-11e5-8ddf-6b6eee32ffee.jpg)

I will try to get a demo

**Comment by msuntharesan** [comment]
here is the [demo pen](http://codepen.io/vanthiyathevan/pen/GJbmrW)

Try resizing the browser and then scroll

**Comment by amcdnl** [comment]
Retest in latest plz

**Comment by GuiHash** [comment]
Lastest version not working for me in Safari but works in Chromium (see capture for Safari bug).
![row-bug](https://cloud.githubusercontent.com/assets/4471444/9488709/ab142b32-4bd3-11e5-8b76-a8936a4673c5.png)

**Comment by amcdnl** [comment]
This should be resolved too now.

**Comment by msuntharesan** [comment]
This is still happening in the following situation
- `scrollbarV: false`
- dt element has no height
- the container element has a height
- no paging

rows outside the container scroll area are double rendered. see this [demo pen](http://codepen.io/vanthiyathevan/pen/GJbmrW)

**Comment by amcdnl** [comment]
I see it, but its not due to same issue as before.  I wonder if its because of the css translate?
